import { Project } from '../types';

export function downloadProjectSpec(project: Project) {
  if (project.downloads?.primary?.url) {
    window.open(project.downloads.primary.url, '_blank');
    return;
  }

  const content = `# Technical Architecture & Project Specification
# ${project.title}
Subtitle: ${project.subtitle}
Domain / Category: ${project.flag || project.category.toUpperCase()}
Status: Production Deployed

---

## 1. Executive Summary & Engineering Problem
${project.problem}

## 2. Engineered Solution
${project.solution}

## 3. Production Metrics & Impact
${project.metrics.map(m => `- ${m.label}: ${m.value}${m.desc ? ` (${m.desc})` : ''}`).join('\n')}

## 4. Key Technical Challenges & Trade-offs
${project.technicalChallenges.map((c, i) => `${i + 1}. ${c}`).join('\n')}

## 5. Core Responsibilities & Contributions
${project.keyContributions.map((k, i) => `- ${k}`).join('\n')}

## 6. Technology Stack
${project.stack.join(', ')}

${project.architecture ? `
## 7. Architecture Pipeline Steps
Flow: ${project.architecture.flowDescription}
${project.architecture.steps.map((s, i) => `Step ${i + 1} [${s.tag || 'Service'}]: ${s.title} - ${s.desc}`).join('\n')}
` : ''}

${project.liveUrl ? `\nLive System URL: ${project.liveUrl}` : ''}
${project.githubUrl ? `\nRepository URL: ${project.githubUrl}` : ''}

---
Generated by Portfolio Engineering Specification Engine · Affandi Agung Laksono
Contact: ccoc.20001@gmail.com
`;

  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${project.id}-technical-specification.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function downloadProjectPackage(project: Project) {
  if (project.downloads?.secondary?.url) {
    window.open(project.downloads.secondary.url, '_blank');
    return;
  }

  if (project.githubUrl) {
    window.open(`${project.githubUrl}/archive/refs/heads/main.zip`, '_blank');
    return;
  }

  const packageManifest = {
    projectName: project.title,
    projectId: project.id,
    domain: project.flag || project.category,
    version: '1.0.0-production',
    author: 'Affandi Agung Laksono',
    contact: 'ccoc.20001@gmail.com',
    liveUrl: project.liveUrl || null,
    githubUrl: project.githubUrl || null,
    stack: project.stack,
    metrics: project.metrics,
    overview: {
      problem: project.problem,
      solution: project.solution,
      technicalChallenges: project.technicalChallenges,
      contributions: project.keyContributions,
    },
    architecture: project.architecture || null,
    deploymentManifest: {
      targetEnvironments: ['Linux VPS', 'AWS EC2 / Lightsail', 'IDCloudHost VPS', 'Vercel / Cloud'],
      webServer: 'Nginx Reverse Proxy with SSL (Let\'s Encrypt)',
      containerRuntime: 'Docker & Docker Compose',
      database: 'PostgreSQL / MySQL / Redis'
    },
    exportTimestamp: new Date().toISOString()
  };

  const content = JSON.stringify(packageManifest, null, 2);
  const blob = new Blob([content], { type: 'application/json;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${project.id}-project-package.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
